/**
 * invoiceNumberGenerator — thin wrapper around idCounterService
 *
 * Format: DBH-YYYY-MM-DD-NNN-CC
 *   NNN = sequence (001→999→1000→…)
 *   CC  = MOD-97 check digit
 *
 * Example: DBH-2026-03-26-001-47
 */

import {
  generateInvoiceNumber as _invoice,
  generateOrderNumber   as _order,
  generateCustomerId    as _customer,
  computeCheckDigit,
} from '../services/idCounterService';
import { logger } from './logger';


/** DBH-YYYY-MM-DD-NNN-CC */
export async function generateInvoiceNumber(_cid?: string, _name?: string): Promise<string> {
  // FIX BUG 9: Removed fallback that used Date.now().slice(-3) — two concurrent
  // submissions within the same millisecond produced identical invoice numbers.
  // Also removed the hardcoded "00" check digit which is always invalid per verifyId().
  // Throw instead so the caller (UI) shows an explicit retry message rather than
  // silently writing an invalid/duplicate invoice number to Firestore.
  return await _invoice();
}

/** ORD-YYYY-MM-DD-NNN-CC */
export async function generateOrderNumber(): Promise<string> {
  // FIX BUG 9: Same collision risk as generateInvoiceNumber — throw instead of fallback.
  return await _order();
}

/** CUST-YYYY-MM-DD-NNN-CC */
export async function generateCustomerNumber(): Promise<string> {
  try {
    return await _customer();
  } catch (e) {
    // FIX H3: Previous fallback used Date.now().slice(-3) (collision-prone when two
    // customers register in the same millisecond) and appended the hardcoded check
    // digit "00", which is always invalid per verifyId() — verifyId() would
    // permanently reject every customer ID generated by this path.
    // Fix: append a 4-char random hex suffix for collision resistance, then compute
    // the correct MOD-97 check digit so downstream ID validation stays consistent.
    //
    // FIX T2R4-H3 (HIGH — predictable random): Was Math.random().toString(16),
    // reverse-engineerable in V8 and prone to collisions when two customer
    // creations fall back simultaneously. Now uses crypto.getRandomValues().
    // (Note: this util is currently unreferenced — verified via grep — but
    // kept on the safe-to-use list rather than deleted, since deletion
    // touches more code than the fix.)
    logger.warn('⚠️ Customer counter unavailable:', e);
    const d = new Date().toISOString().slice(0, 10);
    const buf = new Uint8Array(2);
    crypto.getRandomValues(buf);
    const hexSuffix = Array.from(buf, (b) => b.toString(16).padStart(2, '0')).join('').slice(0, 4);
    const seq = String(Date.now()).slice(-3).padStart(3, '0') + hexSuffix;
    const base = `CUST-${d}-${seq}`;
    return `${base}-${computeCheckDigit(base)}`;
  }
}

/** Sync placeholder — never store in Firestore, display-only before async ID arrives */
export function generateInvoiceNumberSync(_cid?: string, _name?: string): string {
  return `DBH-${new Date().toISOString().slice(0,10)}-PENDING`;
}

// Legacy no-op stubs kept for import compatibility
export function getCustomerCode(_id: string): string | null { return null; }
export function getCustomerInvoiceCount(_c: string, _n: string): number { return 0; }
export function resetInvoiceCounters(): void {}
